plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

def artifactVersion = mod_version.toString()
def artifactBaseName = archives_base_name.toString()

version = artifactVersion
group = maven_group

base {
    archivesName = artifactBaseName
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

sourceSets.main.java.srcDir('../common/src/main/java')
sourceSets.main.java.srcDir('../common/src/minecraft/java')
sourceSets.main.java.srcDir('../common/src/client/java')
sourceSets.main.resources.srcDir('../common/src/main/resources')

processResources {
    inputs.property 'version', artifactVersion
    filesMatching('fabric.mod.json') {
        expand 'version': artifactVersion
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = 'UTF-8'
    options.compilerArgs.add('-Xlint:deprecation')
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    manifest {
        attributes(
                'Implementation-Title': 'The Emerald Standard',
                'Implementation-Version': artifactVersion)
    }
    from('../LICENSE') {
        rename { "${it}_${artifactBaseName}" }
    }
}
