plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

sourceSets.main.java.srcDir('../common/src/main/java')
sourceSets.main.java.srcDir('../common/src/minecraft/java')
sourceSets.main.java.srcDir('../common/src/client/java')
sourceSets.main.resources.srcDir('../common/src/main/resources')

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand 'version': project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = 'UTF-8'
    options.compilerArgs.add('-Xlint:deprecation')
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    manifest {
        attributes(
                'Implementation-Title': 'The Emerald Standard',
                'Implementation-Version': project.version)
    }
    from('../LICENSE') {
        rename { "${it}_${project.archives_base_name}" }
    }
}
