package com.chedidandrew.emeraldstandard.fabric;
import com.chedidandrew.emeraldstandard.core.*; import com.mojang.brigadier.*; import com.mojang.brigadier.arguments.*; import net.minecraft.commands.*; import net.minecraft.network.chat.Component; import net.minecraft.server.level.ServerPlayer; import net.minecraft.world.item.*; import java.util.*;
public final class EmeraldCommands {
 public static void register(CommandDispatcher<CommandSourceStack>d,EconomyService e){ d.register(Commands.literal("emerald")
  .then(Commands.literal("help").executes(c->msg(c,"Commands: market, portfolio, deposit <emeralds>, withdraw <emeralds>, savings deposit|withdraw <emeralds>, buy <ticker> <emeralds>, sell <ticker> <shares>, cd open <emeralds> <30|90|180|365>, cd close, loan fund <emeralds> <term>, loan collect, exchange <resource> <count>")))
  .then(Commands.literal("market").executes(c->market(c,e))).then(Commands.literal("portfolio").executes(c->portfolio(c,e)))
  .then(Commands.literal("deposit").then(Commands.argument("amount",IntegerArgumentType.integer(1)).executes(c->deposit(c,e))))
  .then(Commands.literal("withdraw").then(Commands.argument("amount",IntegerArgumentType.integer(1)).executes(c->withdraw(c,e))))
  .then(Commands.literal("savings").then(Commands.literal("deposit").then(Commands.argument("amount",IntegerArgumentType.integer(1)).executes(c->saving(c,e,true)))).then(Commands.literal("withdraw").then(Commands.argument("amount",IntegerArgumentType.integer(1)).executes(c->saving(c,e,false)))))
  .then(Commands.literal("buy").then(Commands.argument("ticker",StringArgumentType.word()).then(Commands.argument("amount",IntegerArgumentType.integer(1)).executes(c->buy(c,e)))))
  .then(Commands.literal("sell").then(Commands.argument("ticker",StringArgumentType.word()).then(Commands.argument("shares",DoubleArgumentType.doubleArg(.000001)).executes(c->sell(c,e)))))
  .then(Commands.literal("cd").then(Commands.literal("open").then(Commands.argument("amount",IntegerArgumentType.integer(1)).then(Commands.argument("term",IntegerArgumentType.integer(30,365)).executes(c->cd(c,e))))).then(Commands.literal("close").executes(c->bool(c,e.closeCd(player(c).getUUID()),"CD closed","No CD to close"))))
  .then(Commands.literal("loan").then(Commands.literal("fund").then(Commands.argument("amount",IntegerArgumentType.integer(1)).then(Commands.argument("term",IntegerArgumentType.integer(30,365)).executes(c->loan(c,e))))).then(Commands.literal("collect").executes(c->bool(c,e.collectLoan(player(c).getUUID()),"Villager loan collected","Loan is absent or not mature"))))
  .then(Commands.literal("exchange").then(Commands.argument("resource",StringArgumentType.word()).then(Commands.argument("count",IntegerArgumentType.integer(1)).executes(c->exchange(c,e)))) ); }
 static ServerPlayer player(CommandContext<CommandSourceStack>c)throws Exception{return c.getSource().getPlayerOrException();} static int msg(CommandContext<CommandSourceStack>c,String s){c.getSource().sendSuccess(()->Component.literal("[Emerald Standard] "+s),false);return 1;} static int bool(CommandContext<CommandSourceStack>c,boolean ok,String yes,String no){return msg(c,ok?yes:no);}
 static int market(CommandContext<CommandSourceStack>c,EconomyService e){var s=e.state();StringBuilder b=new StringBuilder("Day ").append(s.economicDay).append(" | ").append(s.regime).append(" | Savings ").append(String.format("%.1f%%",EconomyEngine.savingsAnnualRate(s.regime)*100)).append(" | CD ").append(String.format("%.1f%%",EconomyEngine.cdAnnualRate(s.regime)*100)); for(var a:EconomyEngine.ASSETS)b.append(" | ").append(a.ticker()).append(' ').append(String.format("%.2f",s.prices.get(a.ticker())));return msg(c,b.toString());}
 static int portfolio(CommandContext<CommandSourceStack>c,EconomyService e)throws Exception{var id=player(c).getUUID();var a=e.state().account(id);return msg(c,String.format("Cash %.2f | Savings %.2f | CD %.2f | Villager loans %.2f | Net worth %.2f | Holdings %s",a.cashMicro/(double)EconomyState.MICRO,a.savingsMicro/(double)EconomyState.MICRO,a.cdMicro/(double)EconomyState.MICRO,a.loanMicro/(double)EconomyState.MICRO,e.state().netWorth(id),a.shares));}
 static int count(ServerPlayer p,Item item){int n=0;for(int i=0;i<p.getInventory().getContainerSize();i++){ItemStack s=p.getInventory().getItem(i);if(s.getItem()==item)n+=s.getCount();}return n;} static boolean remove(ServerPlayer p,Item item,int n){if(count(p,item)<n)return false;for(int i=0;i<p.getInventory().getContainerSize()&&n>0;i++){ItemStack s=p.getInventory().getItem(i);if(s.getItem()==item){int x=Math.min(n,s.getCount());s.shrink(x);n-=x;}}p.containerMenu.broadcastChanges();return true;}
 static int deposit(CommandContext<CommandSourceStack>c,EconomyService e)throws Exception{int n=IntegerArgumentType.getInteger(c,"amount");var p=player(c);if(!remove(p,Items.EMERALD,n))return msg(c,"Not enough emeralds");e.deposit(p.getUUID(),n);return msg(c,"Deposited "+n+" emeralds");} static int withdraw(CommandContext<CommandSourceStack>c,EconomyService e)throws Exception{int n=IntegerArgumentType.getInteger(c,"amount");var p=player(c);if(e.withdraw(p.getUUID(),n)==0)return msg(c,"Insufficient cash balance");p.getInventory().add(new ItemStack(Items.EMERALD,n));return msg(c,"Withdrew "+n+" emeralds");}
 static int saving(CommandContext<CommandSourceStack>c,EconomyService e,boolean in)throws Exception{int n=IntegerArgumentType.getInteger(c,"amount");return bool(c,e.moveSavings(player(c).getUUID(),n,in),"Savings transfer complete","Insufficient balance");} static int buy(CommandContext<CommandSourceStack>c,EconomyService e)throws Exception{return bool(c,e.buy(player(c).getUUID(),StringArgumentType.getString(c,"ticker"),IntegerArgumentType.getInteger(c,"amount")),"Investment purchased","Purchase failed");} static int sell(CommandContext<CommandSourceStack>c,EconomyService e)throws Exception{return bool(c,e.sell(player(c).getUUID(),StringArgumentType.getString(c,"ticker"),DoubleArgumentType.getDouble(c,"shares")),"Investment sold","Sale failed");}
 static int cd(CommandContext<CommandSourceStack>c,EconomyService e)throws Exception{int term=IntegerArgumentType.getInteger(c,"term");if(term!=30&&term!=90&&term!=180&&term!=365)return msg(c,"CD term must be 30, 90, 180, or 365 days");return bool(c,e.openCd(player(c).getUUID(),IntegerArgumentType.getInteger(c,"amount"),term),"CD opened","CD open failed");} static int loan(CommandContext<CommandSourceStack>c,EconomyService e)throws Exception{return bool(c,e.fundLoan(player(c).getUUID(),IntegerArgumentType.getInteger(c,"amount"),IntegerArgumentType.getInteger(c,"term")),"Villagers received your business loan investment","Loan funding failed");}
 static int exchange(CommandContext<CommandSourceStack>c,EconomyService e)throws Exception{String r=StringArgumentType.getString(c,"resource").toLowerCase();int n=IntegerArgumentType.getInteger(c,"count");Item item;int value;switch(r){case"diamond"->{item=Items.DIAMOND;value=12;}case"diamond_ore"->{item=Items.DIAMOND_ORE;value=12;}case"deepslate_diamond_ore"->{item=Items.DEEPSLATE_DIAMOND_ORE;value=12;}case"gold"->{item=Items.GOLD_INGOT;value=2;}case"raw_gold"->{item=Items.RAW_GOLD;value=2;}case"gold_block"->{item=Items.GOLD_BLOCK;value=18;}case"ancient_debris"->{item=Items.ANCIENT_DEBRIS;value=20;}case"netherite_scrap"->{item=Items.NETHERITE_SCRAP;value=20;}case"netherite"->{item=Items.NETHERITE_INGOT;value=80;}case"emerald_ore"->{item=Items.EMERALD_ORE;value=1;}default{return msg(c,"Unknown exchange resource");}}var p=player(c);if(!remove(p,item,n))return msg(c,"Not enough resources");long proceeds=(long)n*value;e.deposit(p.getUUID(),proceeds);return msg(c,"Exchanged resources for "+proceeds+" emeralds in bank cash");}
}
