package com.chedidandrew.emeraldstandard.core;

import java.util.*;

/** Clearly titled desk features: no fabricated local incidents, named players or world changes. */
final class NewsFeatures {
    record Feature(int outlet,String title,String body) {}
    static final List<Feature> COPY=List.of(
        new Feature(1,"Classifieds: assistant wanted","Wanted: one assistant. Must tolerate repetitive tasks, tight spaces and being described as automation. Previous experience with levers is desirable; previous experience asking who actually does the work is not. Applicants should bring lunch. The machine has no provision for making it."),
        new Feature(3,"Letters: in defense of the ordinary road","Dear Editor: a road is not improved merely by giving it a grand name. I should like one that reaches the place on the sign without crossing my washing. Yours, A Friend of Short Walks. Mabel replies: try delivering the signwriter's lunch by the proposed route."),
        new Feature(0,"The Closing Bell: an affordable forecast","Tomorrow's outlook is available in three editions: optimistic, cautious and revised. The revised edition will be delivered after tomorrow, when it is expected to show exceptional accuracy. Subscribers to all three may congratulate themselves regardless of events. Refunds are subject to a forecast of their own."),
        new Feature(2,"From Our Nether Bureau: packing advice","Pack spare boots, a safe route home and a healthy suspicion of the word shortcut. Leave space for paperwork. It weighs little at departure and accumulates rapidly near customs. Above all, keep the return fare separate from the money you have optimistically set aside for returning goods."),
        new Feature(4,"Advice: what to do with expert advice","First identify the expert. Then identify what the expert is selling. If these steps produce the same answer, you may already understand the advice. Readers needing a second opinion are invited to buy tomorrow's paper, where we shall repeat this procedure with greater urgency."),
        new Feature(3,"Classifieds: dry shed sought","Wanted: a dry shed, ordinary size. No grand frontage required. Must prevent rain reaching objects placed inside it. Previous applicants offered excellent views of the sky; these were declined on technical grounds. Payment by arrangement, preferably after a short but meaningful shower."),
        new Feature(1,"Workshop column: the off switch","The off switch is the part of a machine most often understood by everyone in the room. This makes its omission an interesting design choice. Before investing in an automatic anything, establish whether stopping it is also automatic, or a new profession with its own uniform."),
        new Feature(0,"Advertisements: premium air above the vault","For the discerning account holder: premium space above an impressive vault. Enjoy proximity to wealth without the inconvenience of possessing the contents. Includes an elegant certificate and unlimited opportunities to point downward. Does not include access to whatever you are pointing at."),
        new Feature(2,"Letters from the queue","Dear Bureau: I entered the fast lane and reached the ordinary lane sooner. Is this a successful service? Mara replies: by the most literal reading of the invoice, yes. Keep the receipt. It may prove useful as a fan while you wait for further clarification."),
        new Feature(4,"Corrections: our exclusive horizon","Yesterday's claim that the horizon belonged exclusively to this newspaper was overconfident. The horizon remains visible from several competing locations. We regret the inconvenience to readers who attempted to reserve it. Our exclusive coverage of things beyond it remains equally difficult to verify."),
        new Feature(3,"Garden advice: beginning again","A packet of seeds is not a failed harvest. It is a very small proposal with reasonable prospects if given light, soil and time. Put it somewhere suitable before announcing the banquet. This advice also applies, with minor adjustments, to most village plans."),
        new Feature(1,"Classifieds: prototype for sale","Prototype available: turns a lever when another lever is turned. An excellent introduction to automation, delegation and the difficulty of writing a convincing advertisement. Buyer collects; the automatic delivery attachment remains in development. Includes both levers, but not the person who understands the diagram."),
        new Feature(0,"The Closing Bell: reading the total","A fee of one emerald can sound modest until it has seventeen colleagues. Read the final line before judging the offer by the first. The small print may be small through no fault of the printer: some information simply prefers not to be noticed."),
        new Feature(2,"Bureau advice: the return ticket","A return ticket is a comforting object until one discovers that it assumes the continued existence of the return route. Inspect that assumption. If the bridge is on fire, a beautifully embossed ticket will not improve matters, though it may briefly join the illumination."),
        new Feature(4,"Letters: a strongly held view","Dear Editor: I hold a strongly held view and would like it printed before I discover whether it is correct. Flint replies: our correspondence desk recognizes the genre. Please include a stamped envelope for the equally strongly held revision."),
        new Feature(3,"Classifieds: bench companion","Wanted: someone willing to sit quietly on a bench without turning the afternoon into a public consultation. Applicants may bring a sandwich. Applicants bringing a clipboard should explain its purpose from a respectful distance. No previous experience of sitting is necessary."),
        new Feature(1,"Workshop column: version two","Version two should ideally improve something other than the price. Ask which ordinary task now requires less ordinary effort. If the answer concerns a shinier casing, congratulations: you have found a paint shop with an unusually ambitious vocabulary."),
        new Feature(0,"Advertisements: confidence storage","Do your forecasts take up too much room? Our confidence-storage service holds every prediction securely until one becomes correct. That prediction will then be returned promptly for public display. Incorrect forecasts are retained under a discreet, renewable forgetting fee."),
        new Feature(2,"From Our Nether Bureau: expense forms","An expense form is a tiny journey through a much safer kind of hostile terrain. Carry dates, receipts and a spare explanation. The most difficult crossing is often the box marked miscellaneous, beyond which the accounts desk recognizes neither geography nor hunger."),
        new Feature(4,"Advice: preserving a dramatic headline","Keep it folded away from direct evidence. Excessive contact with ordinary facts can reduce a dramatic headline to a reasonable observation. Should this happen, do not panic. Add the word exclusive and consult a qualified editor before the next edition."),
        new Feature(3,"Letters: thanks for the quiet work","Dear Editor: please leave room for the jobs that end without an incident. Someone keeps the roof sound, puts a tool away and leaves the gate usable. Mabel replies: gladly. A day with fewer exciting problems is not a day with nothing worth reporting."),
        new Feature(1,"Advertisements: deluxe status lamp","At last, a status lamp that indicates whether your status lamp is receiving power. Optional deluxe model includes a lamp to check this lamp. Customers seeking an end to the chain should consult our separate range of windows."),
        new Feature(0,"The Closing Bell: wealth and handwriting","An account does not improve when its numbers are written more elegantly. This is disappointing news for several otherwise promising business plans. We continue to recommend legible figures, especially the figure showing how much remains after the person explaining them has been paid."),
        new Feature(2,"Classifieds: correspondent seeks dry ink","Trade correspondent seeks ink that survives rain, heat and being used to appeal a rejected receipt. Ordinary black preferred. Glowing varieties attract unwelcome attention on the return journey. Seller must quote the delivered price, not the price before the interesting part of delivery.")
    );
    static void day(EconomyState s) {
        if(s.economicDay%2!=0||s.news.stream().anyMatch(a->a.kind()==NewsWire.Kind.FEATURE&&a.day()==s.economicDay))return;
        String title=NewsWire.choose(s,"FEATURE",COPY.stream().map(Feature::title).toList());
        var f=COPY.stream().filter(x->x.title().equals(title)).findFirst().orElseThrow();
        NewsWire.append(s,new NewsWire.Article(s.economicDay,NewsWire.Kind.FEATURE,"FEATURE_"+f.outlet(),
                NewsWire.OUTLETS.get(f.outlet()),"","",0,f.title(),f.body()));
    }
    private NewsFeatures() {}
}
