org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.72

mod_id=the_emerald_standard
mod_name=The Emerald Standard
mod_license=MIT
mod_version=0.2.0-alpha.3
mod_group_id=com.chedidandrew.emeraldstandard
